// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: pkg/protoFiles/chatApp.proto

package protoFiles

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Client sends this for both group and private messages
type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver      string                 `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"` // Empty = broadcast, non-empty = private message
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_pkg_protoFiles_chatApp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protoFiles_chatApp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protoFiles_chatApp_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ChatRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *ChatRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Server sends this back to clients
type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_pkg_protoFiles_chatApp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protoFiles_chatApp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protoFiles_chatApp_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ChatResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_pkg_protoFiles_chatApp_proto protoreflect.FileDescriptor

const file_pkg_protoFiles_chatApp_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/protoFiles/chatApp.proto\x12\n" +
	"protoFiles\"U\n" +
	"\vChatRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1a\n" +
	"\breceiver\x18\x02 \x01(\tR\breceiver\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\":\n" +
	"\fChatResponse\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text2P\n" +
	"\vChatService\x12A\n" +
	"\bChatRoom\x12\x17.protoFiles.ChatRequest\x1a\x18.protoFiles.ChatResponse(\x010\x01B Z\x1echatApplication/pkg/protoFilesb\x06proto3"

var (
	file_pkg_protoFiles_chatApp_proto_rawDescOnce sync.Once
	file_pkg_protoFiles_chatApp_proto_rawDescData []byte
)

func file_pkg_protoFiles_chatApp_proto_rawDescGZIP() []byte {
	file_pkg_protoFiles_chatApp_proto_rawDescOnce.Do(func() {
		file_pkg_protoFiles_chatApp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protoFiles_chatApp_proto_rawDesc), len(file_pkg_protoFiles_chatApp_proto_rawDesc)))
	})
	return file_pkg_protoFiles_chatApp_proto_rawDescData
}

var file_pkg_protoFiles_chatApp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_protoFiles_chatApp_proto_goTypes = []any{
	(*ChatRequest)(nil),  // 0: protoFiles.ChatRequest
	(*ChatResponse)(nil), // 1: protoFiles.ChatResponse
}
var file_pkg_protoFiles_chatApp_proto_depIdxs = []int32{
	0, // 0: protoFiles.ChatService.ChatRoom:input_type -> protoFiles.ChatRequest
	1, // 1: protoFiles.ChatService.ChatRoom:output_type -> protoFiles.ChatResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_protoFiles_chatApp_proto_init() }
func file_pkg_protoFiles_chatApp_proto_init() {
	if File_pkg_protoFiles_chatApp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protoFiles_chatApp_proto_rawDesc), len(file_pkg_protoFiles_chatApp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protoFiles_chatApp_proto_goTypes,
		DependencyIndexes: file_pkg_protoFiles_chatApp_proto_depIdxs,
		MessageInfos:      file_pkg_protoFiles_chatApp_proto_msgTypes,
	}.Build()
	File_pkg_protoFiles_chatApp_proto = out.File
	file_pkg_protoFiles_chatApp_proto_goTypes = nil
	file_pkg_protoFiles_chatApp_proto_depIdxs = nil
}
